# Created by trellis-cli v1.11.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  trellis-test.local:
    site_hosts:
    - canonical: trellis-test.test
      redirects:
      - www.trellis-test.test
    local_path: ../site
    admin_email: admin@trellis-test.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
